server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: HospitalManagementSystem

  security:
    user:
      name: deepak
      password: admin
      roles:
        - ADMIN
        - USER
        - PATIENT
        - DOCTOR

#DB Configuration
  datasource:
    #useSSL=false - its tells not to use SSL (optional to add when false)
    #useSSL=true - its tells to use SSL (Secured connection, it is usually done in PROD )
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hms&useSSL=false
    username: postgres
    password: postgres

#JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format-sql: true
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: ALWAYS
#      data-locations:
#        - 'classpath:patientData.sql'

      #ddl-auto can also be create-drop, create, create-only, truncate, drop, update
      #In production we should keep only
      #Validate : validates and throws errors if discrepancy found between JPA/Entity and Database
      #None : No changes are done to database even if JPA/Entity classes gets updated

      #show-sql is true only in testing environment, mostly false in prod
      #format-sql - prints query in new line for select/update/where clauses to increase readability